---
- name: services | Set id {{ truenas_services_discovered.content | from_json | json_query(jquery) | first }} for {{ outer_item.name }}
  set_fact: 
    ids: "{{ truenas_services_discovered.content | from_json | json_query(jquery) | first }}"
  vars:
    jquery: "[?service == '{{ outer_item.service }}'].id"    

- name: services | Enable services {{ outer_item.name }}
  uri:  
    method: PUT
    headers: 
      Authorization: "Bearer {{ truenas_api_key }}"
    return_content: true
    status_code: 200
    url: "{{ truenas_url + '/api/v2.0/service/id/' + ids }}"
    body: "{{ outer_item.status }}"
    body_format: json
  delegate_to: localhost
