---
- name: systems | Update systems general
  uri:
    method: PUT
    headers:
      Authorization: "Bearer {{ truenas_api_key }}"
    return_content: true
    status_code: 200
    url: "{{ truenas_url + '/api/v2.0/system/general' }}"
    body: "{{ truenas_system_general }}"
    body_format: json
  delegate_to: localhost
  tags:
    - truenas_systems

- name: services | Capturing Existing NTP Servers
  uri:
    method: GET
    headers:
      Authorization: "Bearer {{ truenas_api_key }}"
    return_content: true
    url: "{{ truenas_url + '/api/v2.0/system/ntpserver' }}"
  register: truenas_systems_ntp_found
  delegate_to: localhost
  tags:
    - truenas_systems

- name: services | Setting services Config Fact
  set_fact:
    truenas_systems_ntp_config: "{{ lookup('template', 'systems_ntp_config.yaml.j2') }}"
  tags:
    - truenas_systems

- name: services | debug | Create system ntp
  debug:
    msg:
      - "{{ item }}"
  loop: "{{ truenas_systems_ntp_config | from_json | json_query('create_ntp_servers') }}"
  tags:
    - never

- name: services | debug | Update system ntp
  debug:
    msg:
      - "{{ item }}"
  loop: "{{ truenas_systems_ntp_config | from_json | json_query('update_ntp_servers') }}"
  tags:
    - never

- name: services | debug | Delete system ntp
  debug:
    msg:
      - "{{ item }}"
  loop: "{{ truenas_systems_ntp_config | from_json | json_query('delete_ntp_servers') }}"
  tags:
    - never

- name: systems | Create systems ntp
  uri:
    method: POST
    headers:
      Authorization: "Bearer {{ truenas_api_key }}"
    return_content: true
    status_code: 200
    url: "{{ truenas_url + '/api/v2.0/system/ntpserver' }}"
    body: "{{ item }}"
    body_format: json
  delegate_to: localhost
  loop: "{{ truenas_systems_ntp_config | from_json | json_query('create_ntp_servers') }}"
  tags:
    - truenas_systems

- name: systems | Update systems ntp
  uri:
    method: PUT
    headers:
      Authorization: "Bearer {{ truenas_api_key }}"
    return_content: true
    status_code: 200
    url: "{{ truenas_url + '/api/v2.0/system/ntpserver/id/' + item.id|string }}"
    body: "{{ item.config }}"
    body_format: json
  delegate_to: localhost
  loop: "{{ truenas_systems_ntp_config | from_json | json_query('update_ntp_servers') }}"
  tags:
    - truenas_systems

- name: systems | Delete systems ntp
  uri:
    method: DELETE
    headers:
      Authorization: "Bearer {{ truenas_api_key }}"
    return_content: true
    status_code: 200
    url: "{{ truenas_url + '/api/v2.0/system/ntpserver/id/' + item.id|string }}"
  delegate_to: localhost
  loop: "{{ truenas_systems_ntp_config | from_json | json_query('delete_ntp_servers') }}"
  tags:
    - truenas_systems
